#!/bin/bash
# Copyright (c) 2015 BITPlan GmbH
# WF 2015-02-20 
# build script
. jdk8
grammar="src/main/java/org/sidif/parser/SiDIF.jjt"
touch $grammar 
jjdoc $grammar
mvn clean javacc:jjtree-javacc compile install
