/**
 * Parser as generated from jjtree.
 * See <a href="http://www.sidif.org">http://www.sidif.org</a> for details of SiDIF.
 * The parser {@link org.sidif.parser.jjtree.SiDIF } class is generated by JavaCC.
 */
package org.sidif.parser.jjtree;