/* Generated By:JJTree: Do not edit this line. Link.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.sidif.parser.node;

import org.sidif.parser.jjtree.*;
import org.sidif.parser.jjtree.SiDIF;
import org.sidif.parser.node.SiDIFVisitor;

public
class Link extends SimpleNode {
  private String link;
  private String target;
  private String subject;

  /**
   * @return the link
   */
  public String getLink() {
    return link;
  }

  /**
   * @param link the link to set
   */
  public void setLink(String link) {
    this.link = link;
  }

  /**
   * @return the target
   */
  public String getTarget() {
    return target;
  }

  /**
   * @param target the target to set
   */
  public void setTarget(String target) {
    this.target = target;
  }

  /**
   * @return the subject
   */
  public String getSubject() {
    return subject;
  }

  /**
   * @param subject the subject to set
   */
  public void setSubject(String subject) {
    this.subject = subject;
  }

  public Link(int id) {
    super(id);
  }

  public Link(SiDIF p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SiDIFVisitor visitor, org.sidif.triple.impl.ObjectHolder data) {
    return visitor.visit(this, data);
  }

  /**
   * set a Link with the given subject link and target
   * @param subject
   * @param link
   * @param target
   */
  public void setLink(String subject, String link, String target) {
    this.subject=subject;
    this.link=link;
    this.target=target;
  }

}
/* JavaCC - OriginalChecksum=2ec7d21ab6b9009306f3a53927733e64 (do not edit this line) */
