/**
 * Abstract Syntax Tree nodes.
 * The Abstract Syntax Tree nodes in this package are generated from the jjt grammar definition in {@link org.sidif.parser }.
 * See <a href="http://www.sidif.org">http://www.sidif.org</a> for details of SiDIF.
 * The parser {@link org.sidif.parser.jjtree.SiDIF } class is generated by JavaCC.
 */
package org.sidif.parser.node;