/**
 *
 * This file is part of the https://github.com/BITPlan/org.sidif.triplestore open source project
 *
 * Copyright © 2015-2017 BITPlan GmbH https://github.com/BITPlan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *  You may obtain a copy of the License at
 *
 *  http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Abstract Syntax Tree nodes.
 * The Abstract Syntax Tree nodes in this package are generated from the jjt grammar definition in {@link org.sidif.parser }.
 * See <a href="http://www.sidif.org">http://www.sidif.org</a> for details of SiDIF.
 * The parser {@link org.sidif.parser.jjtree.SiDIF } class is generated by JavaCC.
 */
package org.sidif.parser.node;