/* Generated By:JavaCC: Do not edit this line. SiDIFTreeConstants.java Version 5.0 */
package org.sidif.parser.node;

import org.sidif.parser.jjtree.*;

public interface SiDIFTreeConstants
{
  public int JJTLINKS = 0;
  public int JJTLINK = 1;
  public int JJTVALUE = 2;
  public int JJTLITERAL = 3;


  public String[] jjtNodeName = {
    "Links",
    "Link",
    "Value",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=b36e509f1cfe10614e395534b7c45bef (do not edit this line) */
