/**
 *
 * This file is part of the https://github.com/BITPlan/org.sidif.triplestore open source project
 *
 * Copyright © 2015-2017 BITPlan GmbH https://github.com/BITPlan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *  You may obtain a copy of the License at
 *
 *  http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JavaCC: Do not edit this line. SiDIFTreeConstants.java Version 5.0 */
package org.sidif.parser.node;

import org.sidif.parser.jjtree.*;

public interface SiDIFTreeConstants
{
  public int JJTLINKS = 0;
  public int JJTLINK = 1;
  public int JJTVALUE = 2;
  public int JJTLITERAL = 3;


  public String[] jjtNodeName = {
    "Links",
    "Link",
    "Value",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=b36e509f1cfe10614e395534b7c45bef (do not edit this line) */
